### ISSUE TITLE
Remove dependence on environment variables

### ISSUE THREAD

**Issue by mcdappdev** [skelpo/PayPal#3]
I think it would be nicer if the Provider takes an input of the required keys instead of requiring that they be set to certain env variables. That way it's up to the user to figure out how they get the keys into the provider (maybe it's via JSON file for some project setups, etc) but also makes testing way nicer cause you don't have to set those env variables and can instead spoof those keys.

**Comment by proggeramlug** [comment]
I think you have a fair point, that does seem more flexible.

@calebkleveter thoughts?

**Comment by calebkleveter** [comment]
I agree with this. I'll work that into the next version 👍
